services:
  nano-bots:
    image: nano-bots
    environment:
      ENVIRONMENT: production
      PORT: 3048

      RUN_DANGEROUSLY_AS_SUDO: "false"
      RVM: "false"

      FORCE_SANDBOXED: "true"
      ALLOW_CARTRIDGES_PATH_HEADER: "true"

      NANO_BOTS_ENCRYPTION_PASSWORD: UNSAFE
      NANO_BOTS_END_USER: your-user
      NANO_BOTS_CARTRIDGES_PATH: /cartridges
      # NANO_BOTS_STATE_PATH=/state
      NANO_BOTS_RACK_ATTACK: "false"
      NANO_BOTS_NEW_RELIC: "false"

      COHERE_API_KEY: your-api-key

      # GOOGLE_API_KEY: your-api-key

      # GOOGLE_CREDENTIALS_FILE_PATH: /root/.config/google-credentials.json
      # GOOGLE_PROJECT_ID: your-project-id
      GOOGLE_REGION: us-east4

      MARITACA_API_KEY: 'your-api-key'

      MISTRAL_API_KEY: your-api-key

      OLLAMA_API_ADDRESS: http://localhost:11434

      OPENAI_API_KEY: your-access-token

    ports:
      - 3048:3048

    volumes:
      # - ./google-credentials.json:/root/.config/google-credentials.json
      - /home/your-user/.local/share/nano-bots/cartridges:/cartridges

    # If you are running the Ollama server on your localhost:
    # network_mode: host # WARNING: Be careful, this may be a security risk.
